rewrite for centos6

diff --git a/etc/puppet/files/etc/init.d/PAUSE-httpd-pause-us b/etc/puppet/files/etc/init.d/PAUSE-httpd-pause-us
--- a/etc/puppet/files/etc/init.d/PAUSE-httpd-pause-us
+++ b/etc/puppet/files/etc/init.d/PAUSE-httpd-pause-us
@@ -1,113 +1,80 @@
-#!/bin/sh
+#!/bin/bash
 #
 # Startup script for the Apache Web Server
 #
 # chkconfig: 345 85 15
-# description: Apache is a World Wide Web server.  It is used to serve \
-#	       HTML files and CGI.
+# description: pause httpd on port 81
 # processname: httpd
-# pidfile: /var/run/httpd.pid
-# config: /etc/httpd/conf/access.conf
-# config: /etc/httpd/conf/httpd.conf
-# config: /etc/httpd/conf/srm.conf
-
+# pidfile: /opt/apache/current/logs/httpd.pid
+# config: /opt/apache/current/conf/httpd.conf
 
 # Source function library.
-SLEEP=12
+. /etc/rc.d/init.d/functions
 
-HTTPD8000=/please/supply/path/to/httpd8000
-# HTTPD8000=/usr/local/apache/bin/httpd-ap-1.3.19+ssl-1.42+p-5.6.1+mp-1.25
-# HTTPD8000=/usr/local/apache/bin/httpd-ap-1.3.24+ssl-1.48+p-5.7.3@17165+mp1.27
-# HTTPD8000=/usr/local/apache/bin/httpd-ap-1.3.24+ssl-1.48+p-5.7.3@17273+mp1.27
-# HTTPD8000=/usr/local/apache/bin/httpd-ap-1.3.26+ssl-1.48+p-5.8.0rc2+mp1.27
-# HTTPD8000=/usr/local/apache/bin/httpd-ap-1.3.26+ssl-1.48+p-5.8.0rc3+mp1.27
-# HTTPD8000=/usr/local/apache/bin/httpd-ap-1.3.26+ssl-1.48+p-5.6.1-2+mp-1.27
-HTTPD=/opt/apache/current/bin/httpd
+INITLOG_ARGS=""
+apachectl=/opt/apache/current/bin/apachectl
+httpd=/opt/apache/current/bin/httpd
+prog=PAUSE-httpd
+pidfile=/opt/apache/current/logs/httpd.pid
+lockfile=/var/lock/subsys/PAUSE-httpd
+configfile=/opt/apache/current/conf/httpd.conf
+RETVAL=0
 
-# HTTPD8000=/usr/local/apache/bin/httpd
-HTTPDCONF=/opt/apache/current/conf/httpd.conf
-
+start() {
+        echo -n $"Starting $prog: "
+        $httpd -f ${configfile}
+        RETVAL=$?
+        [ $[$RETVAL] -eq 0 ] && echo "[OK]" || echo "[FAILED]"
+        [ $RETVAL = 0 ] && touch ${lockfile}
+        return $RETVAL
+}
+stop() {
+        echo -n $"Stopping $prog: "
+        if [ -f "${pidfile}" ]; then
+                ps $(cat "${pidfile}" | head -n 1 | sed -r -e 's/^([\d]+)/\1/g') >& /dev/null
+                if [ $[$?] -eq 0 ]; then
+                        kill -TERM $(cat "${pidfile}" | head -n 1 | sed -r -e 's/^([\d]+)/\1/g')
+                        RETVAL=$?
+                else
+                        RETVAL=1;
+                        echo "No process with pid "$(cat "${pidfile}" | head -n 1 | sed -r -e 's/^([\d]+)/\1/g')" was found.   "
+                fi
+        else
+                RETVAL=1;
+                echo -n "No pid file '${pidfile}' was found.   "
+        fi
+        if [ $[$RETVAL] -eq 0 ]; then
+                echo "[OK]" || echo "[FAILED]"
+                rm -f ${lockfile} ${pidfile}
+                echo "Waiting 5 seconds to let apache2 free all resources."
+                sleep 5s
+        fi
+}
 # See how we were called.
 case "$1" in
   start)
-	echo -n "Starting httpd: "
-	nice -11 $HTTPD -f $HTTPDCONF
-	echo
-	touch /var/lock/httpd
-	;;
-  startwithmax1)
-	echo -n "Starting httpd with maxrequestperchild set to 1: "
-	nice -11 $HTTPD -f $HTTPDCONF -DONE_PROCESS
-	echo
-	touch /var/lock/httpd
-	;;
-  start8000)
-	echo -n "Starting httpd8000 ($HTTPD8000): "
-	nice -11 $HTTPD8000 -f $HTTPDCONF -DSWITCH8000
-	echo
-        touch /var/lock/httpd8000
-	;;
-  Xstartgdb)
-	echo -n "Starting httpd under gdb ($HTTPD): "
-        echo -e "set args -f $HTTPDCONF -X -DONE_PROCESS\nhandle SIGPIPE pass\nhandle SIGPIPE nostop\nrun" > xstart.$$.args
-	gdb $HTTPD -x xstart.$$.args
-        rm xstart.$$.args
-	echo
-	;;
-  Xstartgdb8000)
-	echo -n "Starting httpd8000 under gdb ($HTTPD8000): "
-        echo -e "set args -f $HTTPDCONF -DSWITCH8000 -X -DONE_PROCESS\nhandle SIGPIPE pass\nhandle SIGPIPE nostop\nrun" > xstart8000.$$.args
-	gdb $HTTPD8000 -x xstart8000.$$.args
-        rm xstart8000.$$.args
-	echo
-	;;
-  XstartperlDB8000)
-	echo -n "Starting httpd8000 with perl's own -d ($HTTPD8000): "
-	$HTTPD8000 -f $HTTPDCONF -DSWITCH8000 -DPERL_DEBUG -X -DONE_PROCESS
-	echo
-	;;
+        start
+        ;;
   stop)
-	echo -n "Shutting down http: "
-	PIDFILE=/usr/local/apache/logs/httpd.pid
-	[ -f "$PIDFILE" ] && {
-	    kill `cat $PIDFILE`
-	    echo -n httpd
-	}
-	echo
-	rm -f /var/lock/httpd
-	rm -f /var/run/httpd.pid
-	;;
-  stop8000)
-	echo -n "Shutting down http8000: "
-	PIDFILE=/usr/local/apache/logs/httpd.pid.8000
-	[ -f "$PIDFILE" ] && {
-	    kill `cat $PIDFILE`
-	    echo -n httpd8000
-	}
-	echo
-	rm -f /var/lock/httpd8000
-	rm -f /var/run/httpd.pid.8000
-	;;
+        stop
+        ;;
   status)
-	status httpd
-	;;
+	status -p ${pidfile} PAUSE-httpd
+        RETVAL=$?
+        ;;
   restart)
-	$0 stop
-	echo Sleeping $SLEEP seconds
-	sleep $SLEEP
-	$0 start
-	;;
-  reload)
-	echo -n "Reloading httpd: "
-	[ -f /var/run/httpd.pid ] && {
-	    kill -HUP `cat /var/run/httpd.pid`
-	    echo -n httpd
-	}
-	echo
-	;;
+        stop
+        start
+        ;;
+  condrestart)
+        if [ -f ${pidfile} ] ; then
+                stop
+                start
+        fi
+        ;;
   *)
-	echo "Usage: $0 {start|stop|restart|reload|status|start8000|stop8000|Xstartgdb|Xstartgdb8000}"
-	exit 1
+        echo $"Usage: $prog {start|stop|restart|condrestart|help}"
+        exit 1
 esac
 
-exit 0
+exit $RETVAL
